name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker
      uses: uraimo/run-on-arch-action@v1.0.6
      with:
        architecture: arm64v8
        distribution: ubuntu18.04
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}
          docker build -t mavalderrama/kasa:latest . -f Dockerfile
          docker push mavalderrama/kasa:latest
