name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}
        docker buildx -t mavalderrama/kasa:latest . -f Dockerfile --platform linux/amd64,linux/arm64,linux/arm/v7
        docker push mavalderrama/kasa:latest
